/**
 * 两宋文化 · 城市更新 景点数据
 * 聚焦开封（北宋都城）与杭州（南宋都城）
 */
window.SONG_POIS = {
  kaifeng: {
    name: '开封',
    subtitle: '北宋都城 · 八朝古都',
    center: [114.352, 34.795],
    zoom: 13,
    pois: [
      {
        id: 'kf-qingming',
        name: '清明上河园',
        category: 'song',
        tags: ['宋文化', '5A景区'],
        lng: 114.3458,
        lat: 34.8145,
        rating: 4.8,
        address: '开封市龙亭区龙亭西路5号',
        image: 'image/kf-qingming.jpg',
        intro: '清明上河园是以张择端《清明上河图》为蓝本建造的大型宋代文化主题公园，生动再现北宋东京汴梁的市井风貌与繁华盛景，是体验两宋文化的第一站。',
        guide: '建议上午9点入园，先观看「大宋·东京梦华」实景演出（需提前预约）。沿汴河步行，体验宋代市井、勾栏瓦舍与手工作坊。下午可参与「包公断案」互动演出，傍晚灯光亮起时拍照最佳。游览约4–5小时，可与龙亭、天波杨府联游。',
        urbanRenewal: '园区周边开展汴河沿岸风貌整治与城市更新，打通历史水系与文旅动线，实现「以文塑城、以城载文」。'
      },
      {
        id: 'kf-longting',
        name: '龙亭公园',
        category: 'song',
        tags: ['宋文化', '皇家园林'],
        lng: 114.3476,
        lat: 34.8112,
        rating: 4.7,
        address: '开封市龙亭区中山路北段',
        image: 'image/kf-longting.jpg',
        intro: '龙亭原为北宋皇宫所在地，现存清代建筑群坐落于明周王府遗址之上。公园南北中轴清晰，是理解北宋宫城格局与「城摞城」考古奇观的核心区域。',
        guide: '从南门进入，沿中轴线登龙亭大殿，俯瞰潘杨二湖与东京汴梁中轴线。春季牡丹节、秋季菊展为最佳时节。可结合「城摞城」展厅了解六层古城叠压历史。建议游览2–3小时。',
        urbanRenewal: '龙亭片区纳入古城保护与城市更新规划，推进中轴线环境提升与遗址展示设施建设。'
      },
      {
        id: 'kf-kaifengfu',
        name: '开封府',
        category: 'song',
        tags: ['宋文化', '历史建筑'],
        lng: 114.3435,
        lat: 34.7895,
        rating: 4.6,
        address: '开封市包公东湖北岸',
        image: 'image/kf-kaifengfu.jpg',
        intro: '开封府为北宋京都管理机构，包拯任开封府尹期间以铁面无私著称。现建筑为仿宋风格，集中展示宋代司法文化与包公传说。',
        guide: '观看「开衙仪式」与「包公断案」表演（每日定时），参观大堂、牢房、府尹生平展。与包公祠、大相国寺形成「府—祠—寺」文化线路。建议游览2小时。',
        urbanRenewal: null
      },
      {
        id: 'kf-xiangguo',
        name: '大相国寺',
        category: 'song',
        tags: ['宋文化', '佛教'],
        lng: 114.3488,
        lat: 34.7955,
        rating: 4.7,
        address: '开封市鼓楼区自由路西段36号',
        image: 'image/kf-xiangguo.jpg',
        intro: '大相国寺始建于北齐，北宋时为皇家寺院，宋徽宗曾在此礼佛。寺内八角琉璃殿、千手千眼观音像等为重要文物，见证北宋佛教与艺术巅峰。',
        guide: '重点参观天王殿、八角琉璃殿与罗汉堂。晨钟暮鼓时段氛围最佳。寺内素斋可体验。与鼓楼街、书店街步行可达，建议游览1.5–2小时。',
        urbanRenewal: '寺周边历史街区开展微更新，整治立面、改善街巷步行环境，衔接「宋都古城」整体风貌。'
      },
      {
        id: 'kf-tieta',
        name: '铁塔公园',
        category: 'song',
        tags: ['宋文化', '古塔'],
        lng: 114.3652,
        lat: 34.8164,
        rating: 4.6,
        address: '开封市顺河回族区北环路',
        image: 'image/kf-tieta.jpg',
        intro: '铁塔（开宝寺塔）建于北宋皇祐元年，通体铁色琉璃砖结构，被誉为「天下第一塔」，是北宋建筑与琉璃工艺的杰出代表，历经九百余年仍巍然屹立。',
        guide: '登塔远眺（若开放），环绕塔院欣赏砖雕与琉璃细节。春季塔周牡丹、秋季银杏为摄影佳期。可与繁塔、汴京公园串联。建议游览1–1.5小时。',
        urbanRenewal: '铁塔周边开展公园绿地与城市界面更新，强化宋代地标与市民休闲空间的融合。'
      },
      {
        id: 'kf-zhouqiao',
        name: '州桥遗址',
        category: 'renewal',
        tags: ['城市更新', '考古'],
        lng: 114.3482,
        lat: 34.7928,
        rating: 4.5,
        address: '开封市鼓楼区南薰门',
        image: 'image/kf-zhouqiao.jpg',
        intro: '州桥为北宋东京横跨汴河的重要桥梁，《清明上河图》中即有描绘。近年考古发现大量汴河两岸遗址与「海马瑞兽」石雕，是北宋都城水系的直接物证。',
        guide: '参观州桥遗址博物馆（预约制），了解「城摞城」与汴河变迁。结合大相国寺、朱雀门遗址规划线路。建议预留1.5小时，关注官方考古成果展更新。',
        urbanRenewal: '州桥—汴河区域为开封城市更新核心工程，实施考古前置、遗址保护与城市公共空间一体化设计，探索「保护性开发」路径。'
      },
      {
        id: 'kf-shuanglong',
        name: '双龙巷历史街区',
        category: 'renewal',
        tags: ['城市更新', '历史街区'],
        lng: 114.3548,
        lat: 34.7985,
        rating: 4.4,
        address: '开封市龙亭区双龙巷',
        image: 'image/kf-shuanglong.jpg',
        intro: '双龙巷为开封现存较完整的传统胡同群落，近年通过城市微更新保留街巷肌理，植入文创、非遗与社区服务，是「旧貌新颜」传承宋韵的示范案例。',
        guide: '步行探访巷内老宅、非遗工坊与小型展览。适合傍晚漫步拍照。可与鼓楼、书店街组合成半日City Walk。建议游览1–2小时。',
        urbanRenewal: '采用「留改拆」并举策略，修缮传统院落、完善基础设施，让原住民与文旅功能共生，体现城市更新中的文化延续。'
      },
      {
        id: 'kf-jinming',
        name: '金明池遗址',
        category: 'song',
        tags: ['宋文化', '遗址'],
        lng: 114.3315,
        lat: 34.8048,
        rating: 4.3,
        address: '开封市龙亭区金明池',
        image: 'image/kf-jinming.jpg',
        intro: '金明池为北宋皇家水上园林与练兵场，宋徽宗曾在此观看水战演练。遗址公园再现部分水系与景观，是研究北宋皇家园林制度的重要场所。',
        guide: '沿池岸步道游览，春季可赏樱。结合清明上河园理解北宋水系与城市布局。建议游览1小时，适合亲子与轻度徒步。',
        urbanRenewal: '金明池片区水系连通工程为古城水网修复组成部分，推动历史水域与现代城市生态衔接。'
      },
      {
        id: 'kf-shuntian',
        name: '顺天门遗址',
        category: 'renewal',
        tags: ['城市更新', '城门遗址'],
        lng: 114.3295,
        lat: 34.8025,
        rating: 4.4,
        address: '开封市龙亭区',
        image: 'image/kf-shuntian.jpg',
        intro: '顺天门为北宋东京城外城西门，考古发掘揭示完整城门结构。遗址博物馆以数字化手段展示北宋城防与里坊制度，是城市更新中「以遗址定格局」的典范。',
        guide: '参观遗址展示馆与城门复原模型，体验AR复原北宋城门。可与清明上河园、金明池联游。建议游览1小时。',
        urbanRenewal: '顺天门区域实施遗址保护性展示与城市道路、绿地协同更新，构建以西城门为核心的文化展示带。'
      },
      {
        id: 'kf-tianbo',
        name: '天波杨府',
        category: 'song',
        tags: ['宋文化', '杨家将'],
        lng: 114.3452,
        lat: 34.8098,
        rating: 4.5,
        address: '开封市龙亭区龙亭西路',
        image: 'image/kf-tianbo.jpg',
        intro: '天波杨府为北宋抗辽名将杨业府邸，「一门忠烈」故事广为流传。园内展示宋代将门文化与杨家将传说，与龙亭、清明上河园相邻。',
        guide: '观看杨家将主题表演，参观兵器展与府邸建筑。与清明上河园共用区域，可安排半日宋文化主题游。建议游览1.5小时。',
        urbanRenewal: null
      },
      {
        id: 'kf-fanta',
        name: '繁塔',
        category: 'song',
        tags: ['宋文化', '古塔'],
        lng: 114.3608,
        lat: 34.7762,
        rating: 4.4,
        address: '开封市禹王台区繁塔西街',
        image: 'image/kf-fanta.jpg',
        intro: '繁塔（天清寺塔）建于北宋，原为六角九层，现存塔身砖雕佛像千余尊，是开封最古地面建筑之一，见证北宋佛教艺术与城市变迁。',
        guide: '近距离欣赏塔身砖雕，了解「塔身缩小」历史原因。可与禹王台、铁塔形成「古塔之旅」。建议游览40分钟–1小时。',
        urbanRenewal: null
      },
      {
        id: 'kf-baogong',
        name: '包公祠',
        category: 'song',
        tags: ['宋文化', '纪念祠'],
        lng: 114.3415,
        lat: 34.7922,
        rating: 4.5,
        address: '开封市包公湖西畔',
        image: 'image/kf-baogong.jpg',
        intro: '包公祠纪念北宋名臣包拯，祠内碑刻、画像与「清心为治本」等廉文化展陈，体现宋代政治伦理与民间信仰，与包公湖共同构成廉政文化地标。',
        guide: '沿包公湖步行至祠，参观主殿与碑廊。 evening 湖景灯光适宜拍照。与开封府呼应，建议游览1小时。',
        urbanRenewal: '包公湖周边开展水质改善、环湖步道与夜景提升，属古城水系城市更新项目。'
      },
      {
        id: 'kf-citywall',
        name: '开封城墙',
        category: 'renewal',
        tags: ['城市更新', '城墙'],
        lng: 114.3485,
        lat: 34.7865,
        rating: 4.6,
        address: '开封市鼓楼区大梁门',
        image: 'image/kf-citywall.jpg',
        intro: '开封城墙始建于唐代，现存部分为明清重修，仍保留宋代城郭格局影响。城墙马拉松、夜游灯光秀等活动使千年城垣焕发新生。',
        guide: '推荐大梁门登城，骑行或步行城墙环线（部分段开放）。傍晚灯光秀时段体验最佳。建议游览1.5–2小时。',
        urbanRenewal: '城墙内外双修工程推进，包括墙体修缮、护城河整治、城下空间活化，是开封城市更新的标志性项目。'
      },
      {
        id: 'kf-museum',
        name: '开封博物馆',
        category: 'song',
        tags: ['宋文化', '博物馆'],
        lng: 114.3075,
        lat: 34.7972,
        rating: 4.7,
        address: '开封市新区六大街',
        image: 'image/kf-museum.jpg',
        intro: '开封博物馆「城摞城—开宝寺塔」等展陈系统呈现北宋东京城市考古成果，是理解两宋文化物质遗产与城市叠压现象的权威窗口。',
        guide: '重点参观宋代东京城沙盘、出土文物与数字复原展区。免费预约，建议预留2–3小时。适合作为开封宋文化之行的知识起点或总结。',
        urbanRenewal: null
      },
      {
        id: 'kf-hanyuan',
        name: '翰园碑林',
        category: 'song',
        tags: ['宋文化', '书法'],
        lng: 114.3348,
        lat: 34.8215,
        rating: 4.5,
        address: '开封市龙亭区北环路西段',
        image: 'image/kf-hanyuan.jpg',
        intro: '翰园碑林以历代碑刻与书法艺术为主题，收录大量与中原文明、两宋文学相关的碑石摹刻，是开封宋韵文脉的「室外博物馆」。',
        guide: '沿园区碑廊慢行，重点看宋代名家书迹专区。可与铁塔公园同日安排。建议游览1.5–2小时。',
        urbanRenewal: null
      },
      {
        id: 'kf-yanqing',
        name: '延庆观',
        category: 'song',
        tags: ['宋文化', '道教'],
        lng: 114.3468,
        lat: 34.7968,
        rating: 4.5,
        address: '开封市鼓楼区大庆路北侧',
        image: 'image/kf-yanqing.jpg',
        intro: '延庆观始建于金元、承袭北宋东京道教传统，玉皇阁为国内罕见的道教建筑遗存，见证开封作为都城时期的宗教文化格局。',
        guide: '参观玉皇阁与道观院落，体量不大，适合与书店街、大相国寺步行串联。建议1小时。',
        urbanRenewal: '观周边历史街巷纳入古城风貌整治，改善步行可达性与展示标识。'
      },
      {
        id: 'kf-shudian',
        name: '书店街',
        category: 'renewal',
        tags: ['城市更新', '历史街道'],
        lng: 114.3495,
        lat: 34.7958,
        rating: 4.4,
        address: '开封市鼓楼区书店街',
        image: 'image/kf-shudian.jpg',
        intro: '书店街承袭汴京「书肆」传统，是开封古城核心商业街之一。近年经保护性改造，保留街巷尺度与老字号氛围，连接鼓楼、相国寺与州桥片区。',
        guide: '傍晚灯火亮起时最宜散步，可淘书、品开封小吃。与大相国寺、州桥遗址步行可达。建议1–2小时。',
        urbanRenewal: '实施立面管控、管线入地与慢行提升，探索「原住民+文旅」并存的有机更新。'
      },
      {
        id: 'kf-qisheng',
        name: '七盛角',
        category: 'renewal',
        tags: ['城市更新', '文化街区'],
        lng: 114.3445,
        lat: 34.7982,
        rating: 4.4,
        address: '开封市鼓楼区徐府街',
        image: 'image/kf-qisheng.jpg',
        intro: '七盛角为开封古城内新兴宋风文化街区，以仿宋街巷、非遗展演与夜游灯光营造「新宋市井」，是城市更新中文旅业态植入的典型样本。',
        guide: '适合夜晚游览，观看街头表演、打卡仿宋街景。可与开封府、包公祠组线。建议2小时。',
        urbanRenewal: '在历史城区植入文化消费空间，带动徐府街—马道街沿线活力再生。'
      },
      {
        id: 'kf-wansui',
        name: '万岁山武侠城',
        category: 'song',
        tags: ['宋文化', '主题园区'],
        lng: 114.3565,
        lat: 34.8248,
        rating: 4.5,
        address: '开封市龙亭区北环路',
        image: 'image/kf-wansui.jpg',
        intro: '万岁山以北宋皇家苑囿为创意原型，结合武侠演艺与实景互动，是沉浸式体验「东京梦华」市井江湖想象的大型文旅园区。',
        guide: '下午入园，优先观看大型实景演出，夜间灯光与江湖氛围更浓。可与铁塔、翰园联游。建议预留半天。',
        urbanRenewal: null
      },
      {
        id: 'kf-lijing',
        name: '丽景门',
        category: 'renewal',
        tags: ['城市更新', '城门'],
        lng: 114.3398,
        lat: 34.8005,
        rating: 4.6,
        address: '开封市鼓楼区西门大街',
        image: 'image/kf-lijing.jpg',
        intro: '丽景门为开封古城西门标志，城楼高耸、夜景亮化突出，是理解明清城垣格局并衔接宋代东京城记忆的重要城市门户节点。',
        guide: '登城楼远眺护城河与古城天际线，傍晚灯光秀时段拍照最佳。可与城墙环线、金明池方向联游。建议1–1.5小时。',
        urbanRenewal: '城门片区开展墙体修缮、护城河景观与夜游产品打造，强化古城入口形象。'
      },
      {
        id: 'kf-huiguan',
        name: '山陕甘会馆',
        category: 'song',
        tags: ['宋文化', '古建筑'],
        lng: 114.3512,
        lat: 34.7942,
        rating: 4.6,
        address: '开封市鼓楼区徐府街中段',
        image: 'image/kf-huiguan.jpg',
        intro: '山陕甘会馆以砖雕、木雕、石雕闻名，虽主体为明清商会建筑，却坐落于汴京核心街区，是理解开封作为「八朝古都」商贸延续与古城肌理的重要遗存。',
        guide: '细看三雕细节与戏楼，体量紧凑。与七盛角、大相国寺相邻，建议1小时。',
        urbanRenewal: '会馆周边街巷纳入历史街区微更新，提升展示与开放品质。'
      },
      {
        id: 'kf-yuwang',
        name: '禹王台',
        category: 'song',
        tags: ['宋文化', '园林'],
        lng: 114.3685,
        lat: 34.7752,
        rating: 4.3,
        address: '开封市禹王台区禹王台公园',
        image: 'image/kf-yuwang.jpg',
        intro: '禹王台（古吹台）相传为春秋师旷吹奏之地，唐宋以来文人题咏不绝，是开封城东南重要的历史园林与文化记忆点。',
        guide: '园内环境清幽，适合散步与摄影。可与繁塔同日安排东南线。建议1–1.5小时。',
        urbanRenewal: null
      }
    ]
  },
  hangzhou: {
    name: '杭州',
    subtitle: '南宋都城 · 人间天堂',
    center: [120.155, 30.238],
    zoom: 13,
    pois: [
      {
        id: 'hz-westlake',
        name: '西湖',
        category: 'song',
        tags: ['宋文化', '世界遗产'],
        lng: 120.1488,
        lat: 30.2425,
        rating: 4.9,
        address: '杭州市西湖区',
        image: 'image/hz-westlake-photo.jpg',
        intro: '西湖在南宋时期达到审美巅峰，苏堤、断桥、雷峰夕照等景观与诗词绘画共同构成「南宋山水美学」典范，是杭州作为南宋行都最核心的文化符号。',
        guide: '推荐「南宋西湖线」：断桥—白堤—孤山（文澜阁）—苏堤—花港观鱼—雷峰塔。可乘船或骑行。春桃秋桂四季皆美，建议全天或分两日深度游。',
        urbanRenewal: '西湖综合保护工程持续推进，以「保护第一」原则开展景观提升、污水零直排与慢行系统完善。'
      },
      {
        id: 'hz-deshou',
        name: '德寿宫遗址',
        category: 'renewal',
        tags: ['城市更新', '南宋宫城'],
        lng: 120.1712,
        lat: 30.2418,
        rating: 4.8,
        address: '杭州市上城区望江路',
        image: 'image/hz-deshou.jpg',
        intro: '德寿宫为南宋高宗、孝宗退位后居住的「北内」，2022年遗址博物馆开放，是杭州城市更新中「重大遗址原址保护展示」的标杆项目，填补南宋宫城认知空白。',
        guide: '提前预约参观，重点看重华宫正殿遗址、数字化复原与出土文物。与南宋御街、河坊街步行串联。建议游览2小时，讲解器推荐租用。',
        urbanRenewal: '原址保护+博物馆建设模式，带动望江路—中山南路沿线环境整体提升，实现考古、展示与城市功能融合。'
      },
      {
        id: 'hz-yujie',
        name: '南宋御街',
        category: 'renewal',
        tags: ['城市更新', '历史街道'],
        lng: 120.1692,
        lat: 30.2455,
        rating: 4.6,
        address: '杭州市上城区中山中路',
        image: 'image/hz-yujie.jpg',
        intro: '南宋御街为临安城的中轴线商业街，近年经保护性改造恢复青石路面与传统界面，植入文创、非遗与社区商业，是「有机更新」传承南宋市井记忆的样板。',
        guide: '从鼓楼至万松岭，步行探访沿街老铺、博物馆与小型展陈。可与河坊街、德寿宫组合成半日南宋都城Walk。建议游览2–3小时。',
        urbanRenewal: '采用「最小干预」改造策略，保留街巷尺度，改善市政设施，平衡原住民生活与文旅体验。'
      },
      {
        id: 'hz-hefang',
        name: '河坊街',
        category: 'song',
        tags: ['宋文化', '历史街区'],
        lng: 120.1695,
        lat: 30.2408,
        rating: 4.5,
        address: '杭州市上城区河坊街',
        image: 'image/hz-hefang.jpg',
        intro: '河坊街为南宋临安城清河坊遗存，现集胡庆余堂、王星记等老字号与非遗技艺于一体，是体验南宋市井商贸与民俗文化的活态街区。',
        guide: '品尝定胜糕、葱包桧等特色小吃，参观胡庆余堂中药博物馆。傍晚灯笼亮起最具宋韵。与吴山、南宋御街相邻，建议游览2小时。',
        urbanRenewal: '街区开展业态引导与立面管控，避免过度商业化，保持南宋风貌基调。'
      },
      {
        id: 'hz-yuewang',
        name: '岳王庙',
        category: 'song',
        tags: ['宋文化', '爱国'],
        lng: 120.1402,
        lat: 30.2518,
        rating: 4.7,
        address: '杭州市西湖区北山街80号',
        image: 'image/hz-yuewang.jpg',
        intro: '岳王庙纪念南宋抗金名将岳飞，「还我河山」与秦桧跪像成为民族精神象征，与西湖、栖霞岭共同构成南宋忠义文化核心节点。',
        guide: '参观墓域、碑廊与岳飞生平展。可与曲院风荷、苏堤北端联游。建议游览1–1.5小时，注意保持肃穆。',
        urbanRenewal: null
      },
      {
        id: 'hz-leifeng',
        name: '雷峰塔',
        category: 'song',
        tags: ['宋文化', '古塔'],
        lng: 120.1486,
        lat: 30.231,
        rating: 4.6,
        address: '杭州市西湖区南山路15号',
        image: 'image/hz-leifeng.jpg',
        intro: '雷峰塔初建于北宋开宝年间，南宋与白蛇传传说深度绑定。现塔为2002年重建，塔内展示地宫出土文物与五代—宋代佛教艺术，是西湖标志性宋韵景观。',
        guide: '登塔俯瞰西湖全景，参观地宫文物展。傍晚「雷峰夕照」为经典时段。与净慈寺、南屏晚钟相邻。建议游览1.5–2小时。',
        urbanRenewal: '雷峰塔景区周边开展南山路风貌管控与慢行系统优化，强化湖山一体视觉廊道。'
      },
      {
        id: 'hz-liuheta',
        name: '六和塔',
        category: 'song',
        tags: ['宋文化', '古塔'],
        lng: 120.1268,
        lat: 30.1978,
        rating: 4.6,
        address: '杭州市西湖区之江路16号',
        image: 'image/hz-liuheta.jpg',
        intro: '六和塔建于北宋开宝三年，取「六合」之意镇钱塘江潮。塔身砖雕、塔院古刹与江景交融，是南宋临安城外重要佛教地标与观潮胜地。',
        guide: '登塔观钱塘江大桥与江潮（农历八月观潮季最佳）。塔内砖雕值得细品。建议游览1.5–2小时，可与钱塘江沿岸骑行串联。',
        urbanRenewal: null
      },
      {
        id: 'hz-jingci',
        name: '净慈寺',
        category: 'song',
        tags: ['宋文化', '佛教'],
        lng: 120.1482,
        lat: 30.2292,
        rating: 4.5,
        address: '杭州市西湖区南山路56号',
        image: 'image/hz-jingci.jpg',
        intro: '净慈寺为南宋「南屏晚钟」所在地，与雷峰塔隔湖相望。苏轼、杨万里等南宋文人多有题咏，钟声与湖山共同构成南宋禅意美学。',
        guide: '听晚钟（若开放时段），参观大雄宝殿与钟楼。与雷峰塔、苏堤南口步行可达。建议游览1小时。',
        urbanRenewal: null
      },
      {
        id: 'hz-songcheng',
        name: '宋城',
        category: 'song',
        tags: ['宋文化', '主题公园'],
        lng: 120.1045,
        lat: 30.1848,
        rating: 4.7,
        address: '杭州市西湖区之江路148号',
        image: 'image/hz-songcheng.jpg',
        intro: '宋城以南宋临安为创意主线，大型演出《宋城千古情》再现南宋盛景，是沉浸式体验两宋民俗、市井与宫廷文化的综合性文旅项目。',
        guide: '下午入园，优先预约《宋城千古情》场次，穿插宋街市集与互动体验。周末人流较大，建议预留半天。可与六和塔同日安排。',
        urbanRenewal: null
      },
      {
        id: 'hz-museum',
        name: '南宋博物院',
        category: 'song',
        tags: ['宋文化', '博物馆'],
        lng: 120.1705,
        lat: 30.2432,
        rating: 4.8,
        address: '杭州市上城区中山南路',
        image: 'image/hz-museum.jpg',
        intro: '南宋博物院（原南宋官窑博物馆等整合）系统收藏与展示南宋瓷器、书画、金石等，是解读南宋美学与宫廷工艺的最高等级专业机构。',
        guide: '重点参观官窑展区、南宋文物常设展。与德寿宫、御街形成「博物馆+遗址」一日线。免费预约，建议2–3小时。',
        urbanRenewal: '博物院周边开展上城区宋韵文化带建设，串联多处南宋遗址节点。'
      },
      {
        id: 'hz-guanyao',
        name: '南宋官窑博物馆',
        category: 'song',
        tags: ['宋文化', '陶瓷'],
        lng: 120.1485,
        lat: 30.2155,
        rating: 4.6,
        address: '杭州市西湖区南复路60号',
        image: 'image/hz-guanyao.jpg',
        intro: '南宋官窑为皇家制瓷机构，「紫口铁足、青釉如玉」为传世标准。博物馆建在郊坛下官窑遗址上，展示制瓷工艺与出土瓷片，是宋瓷文化的核心载体。',
        guide: '参观龙窑复原、制瓷工序演示与出土标本。可与玉皇山、八卦田组合。建议游览1.5–2小时。',
        urbanRenewal: null
      },
      {
        id: 'hz-huangcheng',
        name: '南宋皇城遗址',
        category: 'renewal',
        tags: ['城市更新', '遗址'],
        lng: 120.1555,
        lat: 30.2205,
        rating: 4.4,
        address: '杭州市上城区凤凰山',
        image: 'image/hz-huangcheng.jpg',
        intro: '南宋皇城依托凤凰山修建，为临安城政治中心。现存遗址以地下为主，凤凰山—馒头山片区开展考古研究与环境提升，逐步构建南宋宫城认知体系。',
        guide: '沿凤凰山步道探访遗址标识与展陈点，结合杭州市区南宋地图理解宫城范围。建议与玉皇山、南宋官窑联游，预留2小时。',
        urbanRenewal: '凤凰山区域实施限高管控、植被恢复与遗址保护展示，是杭州老城「中轴线南段」城市更新的重点片区。'
      },
      {
        id: 'hz-wushan',
        name: '吴山',
        category: 'song',
        tags: ['宋文化', '城隍'],
        lng: 120.1658,
        lat: 30.2382,
        rating: 4.5,
        address: '杭州市上城区吴山广场',
        image: 'image/hz-wushan.jpg',
        intro: '吴山为南宋临安城制高点，城隍阁可俯瞰御街、西湖与凤凰山，是理解南宋都城空间格局的最佳观景点，吴山夜市亦承载老杭州市井记忆。',
        guide: '登城隍阁俯瞰全城，参观宋韵主题展。下山即达河坊街、南宋御街。建议傍晚登阁看日落。游览1.5–2小时。',
        urbanRenewal: '吴山广场及周边开展公共空间品质提升，强化「宋韵杭州」城市界面。'
      },
      {
        id: 'hz-bagua',
        name: '八卦田',
        category: 'song',
        tags: ['宋文化', '皇家农坛'],
        lng: 120.1552,
        lat: 30.2148,
        rating: 4.4,
        address: '杭州市上城区虎玉路',
        image: 'image/hz-bagua.jpg',
        intro: '八卦田为南宋皇家籍田（祭农之地），呈八卦形分区种植，体现「以农为本」的治国理念，是南宋礼仪制度与农业文化的独特遗存。',
        guide: '沿玉皇山步道抵达，四季田景各异。春季油菜、秋季稻浪适合摄影。可与南宋官窑博物馆同日游览。建议1小时。',
        urbanRenewal: '八卦田周边实施景观农田保护与城市边缘空间生态修复，衔接凤凰山文化带。'
      },
      {
        id: 'hz-lingyin',
        name: '灵隐寺',
        category: 'song',
        tags: ['宋文化', '佛教'],
        lng: 120.1012,
        lat: 30.2428,
        rating: 4.8,
        address: '杭州市西湖区法云弄1号',
        image: 'image/hz-lingyin.jpg',
        intro: '灵隐寺为江南著名古刹，两宋时期香火鼎盛，高僧往来频繁。与飞来峰造像群共同构成杭州佛教文化核心，是理解南宋临安宗教格局的重要节点。',
        guide: '建议早入园避开人流，重点参观天王殿、大雄宝殿与飞来峰石窟。可与北高峰、植物园联游。预留3–4小时。',
        urbanRenewal: null
      },
      {
        id: 'hz-feilai',
        name: '飞来峰',
        category: 'song',
        tags: ['宋文化', '石窟'],
        lng: 120.0985,
        lat: 30.2415,
        rating: 4.7,
        address: '杭州市西湖区灵隐路',
        image: 'image/hz-feilai.jpg',
        intro: '飞来峰摩崖造像始凿于五代，两宋续有开凿，弥勒、观音等造像精美，是江南少见的石窟艺术遗存，与灵隐寺一体游览。',
        guide: '沿冷泉溪观摩崖造像，注意保护文物、勿触碰。与灵隐寺同票区，建议合并安排2小时。',
        urbanRenewal: null
      },
      {
        id: 'hz-baochu',
        name: '保俶塔',
        category: 'song',
        tags: ['宋文化', '古塔'],
        lng: 120.1436,
        lat: 30.2633,
        rating: 4.6,
        address: '杭州市西湖区宝石山',
        image: 'image/hz-baochu.jpg',
        intro: '保俶塔立于宝石山巅，五代吴越始建、两宋沿革，纤细塔影为西湖标志之一，与雷峰塔「一南一北」构成湖山对景。',
        guide: '从断桥或黄龙洞方向登山，登高俯瞰北里湖。日落前后光线最佳。建议1.5–2小时。',
        urbanRenewal: '宝石山—北山街沿线持续风貌管控与慢行提升，强化湖山视觉廊道。'
      },
      {
        id: 'hz-sudi',
        name: '苏堤',
        category: 'song',
        tags: ['宋文化', '西湖'],
        lng: 120.1395,
        lat: 30.2398,
        rating: 4.8,
        address: '杭州市西湖区苏堤',
        image: 'image/hz-sudi.jpg',
        intro: '苏堤为苏轼知杭州时所筑，「苏堤春晓」位列西湖十景之首，是北宋文人治湖与南宋山水审美的经典叠加景观。',
        guide: '骑行或步行纵贯六桥，春季桃花杨柳最盛。可与花港、雷峰塔、岳庙串联。建议2–3小时。',
        urbanRenewal: '纳入西湖综合保护，维持堤岸植被与慢行品质，限制机动车干扰。'
      },
      {
        id: 'hz-gushan',
        name: '孤山·文澜阁',
        category: 'song',
        tags: ['宋文化', '藏书'],
        lng: 120.1428,
        lat: 30.2535,
        rating: 4.6,
        address: '杭州市西湖区孤山路',
        image: 'image/hz-gushan.jpg',
        intro: '孤山为湖中岛屿，南宋以来文人荟萃；文澜阁曾藏《四库全书》，与西泠印社共同延续两宋以降的书卷与金石传统。',
        guide: '白堤步行上岛，参观文澜阁、中山公园与西泠印社。适合半日文化漫步。',
        urbanRenewal: null
      },
      {
        id: 'hz-santan',
        name: '三潭印月',
        category: 'song',
        tags: ['宋文化', '西湖十景'],
        lng: 120.1448,
        lat: 30.2372,
        rating: 4.7,
        address: '杭州市西湖区小瀛洲',
        image: 'image/hz-santan.jpg',
        intro: '三潭印月为西湖十景，岛上庭园与湖中石塔相映。虽历代修缮，其审美意象与南宋西湖游赏传统一脉相承，是湖心宋韵的象征。',
        guide: '需乘船登岛，夜间亮灯时「印月」意境更佳。建议与游船线路一并安排，约1.5小时。',
        urbanRenewal: null
      },
      {
        id: 'hz-qianwang',
        name: '钱王祠',
        category: 'song',
        tags: ['宋文化', '祠庙'],
        lng: 120.1492,
        lat: 30.2385,
        rating: 4.4,
        address: '杭州市上城区南山路',
        image: 'image/hz-qianwang.jpg',
        intro: '钱王祠纪念吴越钱氏，钱俶纳土归宋后杭州平稳入宋，是理解「吴越—两宋」历史转折与杭州城市延续的重要纪念地。',
        guide: '与柳浪闻莺、涌金公园相邻，适合湖滨步行线。建议1小时。',
        urbanRenewal: '湖滨—南山路沿线公共空间品质提升，强化历史文化展示。'
      },
      {
        id: 'hz-wansong',
        name: '万松书院',
        category: 'song',
        tags: ['宋文化', '书院'],
        lng: 120.1525,
        lat: 30.2255,
        rating: 4.5,
        address: '杭州市上城区万松岭路',
        image: 'image/hz-wansong.jpg',
        intro: '万松书院位于凤凰山万松岭，明清鼎盛，地近南宋皇城与太学旧地，今以「梁祝」传说与书院建筑群闻名，是南宋文教空间记忆的延伸。',
        guide: '登山访书院，可与南宋皇城遗址、八卦田组线。建议1.5小时。',
        urbanRenewal: '万松岭—凤凰山文化带推进步道与遗址标识系统建设。'
      }
    ]
  }
};
